// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"crud_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/query/:uid",
				Handler: GetCatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/newcat",
				Handler: NewCatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/editcat",
				Handler: EditCatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/deletecat",
				Handler: DeleteCatHandler(serverCtx),
			},
		},
	)
}
