// Code generated by goctl. DO NOT EDIT.
package types

type CatReq struct {
	Uid uint `path:"uid"`
}

type CatReqPost struct {
	Uid uint `json:"uid"`
}

type Cat struct {
	Uid  uint   `json:"uid"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type ErrResp struct {
	Err int `json:"err"`
}
